import google.generativeai as genai
import os
import streamlit as st
from dotenv import load_dotenv

# Load .env for local development
load_dotenv()

# Get API key from Streamlit Secrets (Cloud) or .env (Local)
API_KEY = st.secrets.get("GOOGLE_API_KEY") or os.getenv("GOOGLE_API_KEY")

if not API_KEY:
    raise ValueError("GOOGLE_API_KEY not found.")

genai.configure(api_key=API_KEY)

model = genai.GenerativeModel("gemini-2.0-flash")


def ask_gemini(context, question):

    prompt = f"""
You are an expert Indian Legal Assistant.

Use ONLY the legal context provided below.

If the answer is present, explain it in simple language.

Mention the Article number whenever possible.

If multiple context chunks are provided, combine them.

If the answer is truly absent, reply:
"I could not find this information in the provided legal documents."

Legal Context:
{context}

Question:
{question}

Answer:
"""

    try:
        response = model.generate_content(prompt)

        if hasattr(response, "text") and response.text:
            return response.text

        return "No response generated by Gemini."

    except Exception as e:
        return f"Error: {e}"