import google.generativeai as genai
import os
from dotenv import load_dotenv

load_dotenv()

genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

model = genai.GenerativeModel("gemini-flash-latest")


def ask_gemini(context, question):

    prompt = f"""
You are an expert Indian Legal Assistant.

Use ONLY the legal context provided below.

If the answer is present, explain it in simple language.

Mention the Article number whenever possible.

If multiple context chunks are provided, combine them.

If the answer is truly absent, reply:
"I could not find this information in the provided legal documents."

Legal Context:
{context}

Question:
{question}

Answer:
"""

    try:
        response = model.generate_content(prompt)

        if hasattr(response, "text") and response.text:
            return response.text

        return "No response generated by Gemini."

    except Exception as e:
        return f"Error: {e}"